# Guess the value which is a random integer[1,100] generated by computer.

import random         # make random module available

answer = random.randint(1, 10)  # Generate an correct answer

n = 1
gue_an = 0        # guessed answer
while gue_an != answer:
    gue_an = int(input(f"Guess {n}: "))
    if gue_an < answer:
        print("   Clue:higher")
        n += 1
    elif gue_an > answer:
        print("   Clue:lower")
        n += 1
                 # Correct answer guessed
if n < 3:
    print(f"   Correct answer after only {n} guesses - Excellent!.")
else:
    print(f"   Correct answer after {n} guesses.")
